apiVersion: v1
data:
  # This part comes from the cluster and shou
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::878321264576:role/node-group-1-eks-node-group-20240403114700312700000001
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::878321264576:role/node-group-2-eks-node-group-20240403114700312700000002
      username: system:node:{{EC2PrivateDNSName}}

  # this is the part where every user has to be added
  mapUsers: |
    - userarn: arn:aws:iam::878321264576:user/workshop-1
      username: workshop
      groups:
      - workshop
kind: ConfigMap
metadata:
  creationTimestamp: "2024-04-03T11:58:04Z"
  name: aws-auth