---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workshop
rules:
  - apiGroups: ["*"]
    resources: ["deployments", "configmaps", "pods", "secrets", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workshop
subjects:
  - kind: Group
    name: workshop
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: workshop
  apiGroup: rbac.authorization.k8s.io
